version: "3"

services:
    drupal:
        image: drupal
        ports:
            - 5000:80
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
    postgres:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=pass123

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
